# Generated by Django 5.1.6 on 2025-02-18 15:10

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=220)),
                ('parent_phone', models.CharField(max_length=11)),
                ('facebook_page', models.URLField(default='')),
                ('symptoms', models.TextField(default='')),
                ('allergies', models.TextField(default='')),
                ('medications', models.TextField(default='')),
                ('past_medical_history', models.TextField(default='', verbose_name='التاريخ الطبى السابق')),
                ('last_oral_intake', models.TextField(default='', verbose_name='اخر وجبه تناولها المريض')),
                ('events', models.TextField(default='')),
                ('blood', models.CharField(choices=[('O-', 'O-'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('A-', 'A-'), ('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+')], max_length=4)),
                ('health_data', models.TextField(default='')),
                ('health_record', models.TextField(default='')),
                ('chronic_disease', models.TextField(default='')),
                ('test_result', models.TextField(default='')),
                ('health_insurance', models.TextField(default='')),
                ('doctor_notes', models.TextField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
    ]
