# Generated by Django 5.1.6 on 2025-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blood',
            field=models.CharField(choices=[('O-', 'O-'), ('B-', 'B-'), ('A-', 'A-'), ('O+', 'O+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A+', 'A+'), ('AB+', 'AB+')], max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
