# Generated by Django 5.1.6 on 2025-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_blood_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blood',
            field=models.CharField(choices=[('B+', 'B+'), ('AB-', 'AB-'), ('A-', 'A-'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('A+', 'A+'), ('O+', 'O+')], max_length=4),
        ),
    ]
