# Generated by Django 5.1.6 on 2025-03-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_image_alter_customuser_blood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blood',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='chronic_disease',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='doctor_notes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='events',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='health_data',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='health_insurance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='health_record',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_oral_intake',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='past_medical_history',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_result',
        ),
    ]
